
PEV07 = struct();

PEV07.id = "PEV07";
% DAY 1 --> No experiments were done on the PEV05 on Day 1

% Day 2
    DAY = 2;
    PEV07.DAY(DAY).Date = Experimental_days(2);
    
    % Experiment 1
    EXPERIMENT = 1;
    PEV07.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV07_S1B__ECG_timeline_20260129_144435.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV07_S1B__STIM_EVENTS_20260129_144435.csv");
    
    [PEV07.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV07.DAY(DAY).Experiment(EXPERIMENT).current_value = '10uA';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 10 uA';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 2
    EXPERIMENT = 2;
    PEV07.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV07_S2_ECG_timeline_20260129_144648.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV07_S2_STIM_EVENTS_20260129_144648.csv");
    
    [PEV07.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV07.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).description = 'Pulse train';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 3
    EXPERIMENT = 3;
    PEV07.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV07_S3_ECG_timeline_20260129_144844.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV07_S3_STIM_EVENTS_20260129_144844.csv");
    
    [PEV07.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV07.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).description = 'Pulse train';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 4
    EXPERIMENT = 4;
    PEV07.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(2);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV07_S4_ECG_timeline_20260129_145104.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV07_S4_STIM_EVENTS_20260129_145104.csv");
    
    [PEV07.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV07.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).description = 'Pulse train';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 5
    EXPERIMENT = 5;
    PEV07.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV07_V1_ECG_timeline_20260129_143315.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV07_V1_STIM_EVENTS_20260129_143315.csv");
    
    [PEV07.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV07.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).description = 'Visual';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 6
    EXPERIMENT = 6;
    PEV07.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV07_C1_ECG_timeline_20260129_143706.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV07_C1_STIM_EVENTS_20260129_143706.csv");
    
    [PEV07.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV07.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV07.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).description = 'Control';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV07.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';
