
PEV06 = struct();

PEV06.id = "PEV06";
% DAY 1 --> No experiments were done on the PEV05 on Day 1

% Day 2
    DAY = 2;
    PEV06.DAY(DAY).Date = Experimental_days(2);
    
    % Experiment 1
    EXPERIMENT = 1;
    PEV06.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_S1_ECG_timeline_20260129_131112.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_S1_STIM_EVENTS_20260129_131112.csv");
    
    [PEV06.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV06.DAY(DAY).Experiment(EXPERIMENT).current_value = '10uA';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 10 uA';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 2
    EXPERIMENT = 2;
    PEV06.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_S2_ECG_timeline_20260129_131423.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_S2_STIM_EVENTS_20260129_131423.csv");
    
    [PEV06.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV06.DAY(DAY).Experiment(EXPERIMENT).current_value = '1uA';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 1 uA';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 3
    EXPERIMENT = 3;
    PEV06.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_S3_ECG_timeline_20260129_131736.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_S3_STIM_EVENTS_20260129_131736.csv");
    
    [PEV06.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV06.DAY(DAY).Experiment(EXPERIMENT).current_value = '1uA';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 1 uA';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 4
    EXPERIMENT = 4;
    PEV06.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(2);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_V1_ECG_timeline_20260129_132328.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_V1_STIM_EVENTS_20260129_132328.csv");
    
    [PEV06.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV06.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).description = 'Visual Stimulation';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 5
    EXPERIMENT = 5;
    PEV06.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_C1_ECG_timeline_20260129_132622.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV06\PEV06_C1_STIM_EVENTS_20260129_132622.csv");
    
    [PEV06.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV06.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV06.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).description = 'Control';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV06.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';
