
PEV04 = struct();

PEV04.id = "PEV04";
% DAY 1
    DAY = 1;
    PEV04.DAY(DAY).Date = Experimental_days(1);
    
    % Experiment 1
    EXPERIMENT = 1;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D1\P2_PEV04_ECG_timeline_20260121_114937.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D1\P2_PEV04_STIM_EVENTS_20260121_114937.csv");
    
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '40nA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 40 nA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 2
    EXPERIMENT = 2;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D1\P3_PEV04_ECG_timeline_20260121_115658.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D1\P3_PEV04_STIM_EVENTS_20260121_115658.csv");
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '10 uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 10 uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 3
    EXPERIMENT = 3;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D1\P4_PEV04_ECG_timeline_20260121_120405.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D1\P4_PEV04_STIM_EVENTS_20260121_120405.csv");    
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '10uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current with pulse train of 10 uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = 'N';

% DAY 2
DAY = 2;
PEV04.DAY(DAY).Date = Experimental_days(2);

    % Experiment 1
    EXPERIMENT = 1;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV04_S1_ECG_timeline_20260129_111942.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV04_S1_STIM_EVENTS_20260129_111942.csv");
    
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);
   
    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '10uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 10 uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 2
    EXPERIMENT = 2;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV04_S2_ECG_timeline_20260129_112406.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV04_S2_STIM_EVENTS_20260129_112406.csv");
    
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '1uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 1 uA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 3
    EXPERIMENT = 3;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(1);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV04_S3_ECG_timeline_20260129_112833.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV04_S3_STIM_EVENTS_20260129_112833.csv");
    
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '100nA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Electrical Stimulation Current of 100 nA';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';
    
    % Experiment 4
    EXPERIMENT = 4;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(2);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV04_V1_1ms_60s_ECG_timeline_20260129_110655.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV04_V1_1ms_60s_STIM_EVENTS_20260129_110655.csv");
    
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);

    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Visual Stimulation 1 ms duration';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

    % Experiment 5
    EXPERIMENT = 5;
    PEV04.DAY(DAY).Experiment(EXPERIMENT).type = Experimental_types(3);
    datos_bio = readtable("..\Verificacion_stim_sense\D2\PEV04_C1_bien_ECG_timeline_20260129_111436.csv");
    datos_STIM = readtable("..\Verificacion_stim_sense\D2\PEV04_C1_bien_STIM_EVENTS_20260129_111436.csv");
    
    [PEV04.DAY(DAY).Experiment(EXPERIMENT).CH1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).CH2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).stim_OFF, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t1, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).t2, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_ON, ...
        PEV04.DAY(DAY).Experiment(EXPERIMENT).idx_events_OFF, ...
        ] = extract_channel_and_stimulation(datos_bio, datos_STIM);
    
    PEV04.DAY(DAY).Experiment(EXPERIMENT).current_value = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).description = 'Control protocol';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).pulse_width = '';
    PEV04.DAY(DAY).Experiment(EXPERIMENT).number_of_pulses = '';

% DAY 3 --> No experiments were done on the PEV04 on Day 3
DAY = 3;
PEV04.DAY(DAY).Date = Experimental_days(3);
